export const COUNTER_INCREMENT = 'COUNTER_INCREMENT';
export const COUNTER_DECREMENT = 'COUNTER_DECREMENT';

export const COUNTER_ADD = 'COUNTER_ADD';
export const COUNTER_SUBSTRACT = 'COUNTER_SUBSTRACT';
export const COUNTER_MULTIPLY = 'COUNTER_MULTIPLY';
export const COUNTER_DIVIDE = 'COUNTER_DIVIDE';

export const COUNTER_CLEAR = 'COUNTER_CLEAR';

